siteTitle = "Axel Clark"
siteDescr = "The personal website of Axel Clark"
siteAuthor = "Axel Clark"

siteTwitterUrl = "https://twitter.com/axelclark2"
siteGithubUrl = "https://github.com/axelclark"

googleAnalyticsId = ""

linkPrefix = "/axelclark"
